### ISSUE TITLE
Generating API Documentation doesn't work in some areas

### ISSUE THREAD

**Issue by MattBred** [thecodingmachine/graphqlite#328] opened 2021-02-10 22:12 UTC
In a controller, if I make a query or mutation and add a comment to the docblock, this comment is parsed and added to the API documentation. Likewise if I add a comment to a field in a type.

However, if I have a type that uses [external type declaration](https://graphqlite.thecodingmachine.io/docs/external_type_declaration) and have `@SourceField` fields, I cannot get the documentation to work. Even adding a comment to the original entity doesn't work.

Another part that doesn't work is factories that create input types. I can't seem to be able to get my comments to show up in the generated API documentation.

Is there something I'm doing wrong, or is this just not supported yet?

**Comment by MattBred** [comment] 2021-02-15 21:55
@moufmouf Any input on this?

**Comment by oojacoboo** [comment] 2021-03-29 13:12
AFAIK many of the comments aren't added.  There was some discussion around this.  They should NEVER be added.  Instead, there should be a defined annotation for comments exposed over the schema.  PHPDoc comments could contains internals and should not be used within the schema docs.

I don't know what the status is currently on this addition.  Maybe @moufmouf can clarify.

**Comment by oojacoboo** [comment] 2021-03-29 15:56
Closing this as duplicate of #289

**Closed by oojacoboo** 2021-03-29 15:56 UTC
Labels: duplicate, enhancement
