### ISSUE TITLE
Cannot override Field methods

### ISSUE THREAD

**Issue by Zheness** [thecodingmachine/graphqlite#34] opened 2019-04-05 14:46 UTC
Hello,

My entity Company has many Members.
I created a new method `members()` in `CompanyType.php` but it seems that my method is never called. Only the parent one which return a `Porpaginas` result is called.

Even if i deactivate the main field with `getMembersFiled()->hide()` it doesn't work.

Any idea on how to solve ?

Thanks !

**Comment by moufmouf** [comment] 2019-04-09 10:03
Weird. I cannot reproduce the problem.

I tried to create a field in a "@Type" and override it in a "@ExtendType" and the field is indeed overridden...

**Comment by moufmouf** [comment] 2019-04-11 09:51
This was fixed in TDBM-GraphQL.
Caused by 2 @ExtendType class inheriting each other while also referencing inherited types.

See https://github.com/thecodingmachine/tdbm-graphql/pull/33

**Closed by moufmouf** 2019-04-11 09:51 UTC
