### ISSUE TITLE
After pulling new code from repo, cannot map class

### ISSUE THREAD

**Issue by football2801** [thecodingmachine/graphqlite#267] opened 2020-05-28 17:19 UTC
My GraphQL setup has been working properly in production since the first push. We've added a new notification feature that is tied into the employee object. The new entity contains the proper ```@Type()``` annotation, and everything works in dev. Upon pulling code to production, we get the following error:
```For return type of App\Entity\Marketing\Employee::getNotifications, cannot map class "App\Entity\Marketing\Notification" to a known GraphQL type. Check your TypeMapper configuration```

Is there a cache I can clear outside of symfony's ```php bin/console cache:clear``` to get this error to go away and get the new entity to be read properly?

**Comment by moufmouf** [comment] 2020-06-01 14:31
Weird... This indeed seems cache related. A possibility might be that the APCu cache (that is specific to Apache or NGinx) is not purgeable from the command line?
Is there any way you can restart your webserver to check this?

**Comment by football2801** [comment] 2020-06-04 22:41
Looks like it works after rebooting the entire webserver. This is a CentOS 8 Machine if that helps at all

**Comment by football2801** [comment] 2020-06-12 16:49
@moufmouf Is there a way to manually clear a cache to prevent a reboot of the webserver?

**Comment by football2801** [comment] 2020-06-29 14:02
@moufmouf I just deployed to CentOS7 server and made ```@Type``` change to a model. After running the cache clear command, I still had to reboot the webserver, so it is not CentOS8 specific. 

Hopefully you can track down this issue. Rebooting a webserver for a code change is not ideal.

**Comment by moufmouf** [comment] 2020-06-30 07:13
@football2801 From the screenshot you are sending, it seems to me that APCu is installed, and I'm almost certain this is the root cause. Indeed, APCu cache is not shared between Apache (or PHP-FPM) and the CLI. So purging the cache in the CLI does not purge the cache in the web-server. This is quite a common problem.
The way the cache is configured also depends on the GraphQLite integration you are using. What framework are you using? Symfony? Laravel? Something else?

**Comment by moufmouf** [comment] 2020-06-30 07:15
Also, this thread on StackOverflow is clearly related to the problem: https://stackoverflow.com/questions/39981501/how-to-clear-doctrine-apc-cache-for-production

**Comment by football2801** [comment] 2020-06-30 13:14
@moufmouf, thanks for getting back with me. I can confirm that the server does not have APCu cache enabled.
I've attached another picture so you can see what the profiler is indicating. Green with a checkmark means it is installed and active, Gray with an X means it's not installed and inactive. Red with an X means it's installed but inactive.
![image](https://user-images.githubusercontent.com/30697421/86129903-64b85080-bab1-11ea-9e60-415556c72b95.png)

I've also double checked Symfony's profiler by looking at the phpinfo page, and I can confirm that the profiler is accurate.

We are running on Symfony using thecodingmachine/graphqlite-bundle v4.0.6

**Comment by brettins** [comment] 2020-09-29 23:41
I'm having trouble with this. Has there ben any solution or update?

**Comment by football2801** [comment] 2020-10-01 20:54
@brettins, there have been no updates by @moufmouf. I have to reboot the entire webserver to make graphql updates.

**Comment by brettins** [comment] 2020-10-02 08:12
Ok thanks. I'm seeing this error on Ubunutu 18.04 and have to reboo the entire server to make graphql updates as well.

**Comment by mailopl** [comment] 2021-03-23 12:37
It's happening for me too. No APC. Opcache enabled (restarting FPM changes nothing, restarting whole server works). Will let you know in few days if using opcache clear tool fixes it.

**Comment by mailopl** [comment] 2021-03-25 09:20
What doesn't work:
- restarting fpm
- using opcache tool
- clearing app cache 
- /tmp/graphqlite.* cache
- clearing redis cache
- dumping composer autoload

**Comment by oojacoboo** [comment] 2021-03-29 16:09
I'm uncertain of how this is not a cache issue when restarting the server resolves the issue.

**Comment by brettins** [comment] 2021-03-29 16:30
I think it is clear that it is a caching issue, @oojacoboo, but all the normal ways of clearing the cache do not work, so is it possible that the graphqlite code is interacting with the cache in a strange way, or keeping its own cache manually in an unexpected place that isn't cleared until system restart? Maybe a file in /tmp that has a randomly generated name that isn't under the graphql folder?

**Comment by oojacoboo** [comment] 2021-03-29 16:50
I've seen this error before, but know I've been able to clear the cache to resolve.  I've specifically found this bin script to be helpful in ensure cache is fully and properly cleared.

https://github.com/gordalina/cachetool

We're using the following:

```
bin/cachetool.phar apcu:cache:clear
bin/cachetool.phar opcache:reset
```

Could you try this tool and see if you're still having issues?

**Comment by xhuberty** [comment] 2021-08-05 13:17
I'm facing the same issue (with Symfony) and from what I found I can confirm that is a cache issue. I didn't use cachetool but restarting the webserver fix it. This is not a viable solution when we will go live.

**Comment by skurovec** [comment] 2021-08-05 13:30
Yesterday I have encountered this as well, and maybe found a solution. In bundle configuration (if you are using bundle) in file _./vendor/thecodingmachine/graphqlite-bundle/Resources/config/container/graphqlite.xml_ is defined service **graphqlite.phpfilescache** which uses PhpFilesAdapter. 

This is default case when there is not another cache activated. But it has only one parameter in configuration - namespace. Third parameter is directory, and when empty it users system temp directory. 

Try to add cache dir as (third) parameter and it should work. 

```        
    <service id="graphqlite.phpfilescache" class="Symfony\Component\Cache\Adapter\PhpFilesAdapter">
            <argument>graphqlite</argument>
            <argument>0</argument>
            <argument>%kernel.cache_dir%</argument>
    </service>
```

**Comment by mailopl** [comment] 2021-08-05 14:36
Super interested if this will work too!

**Comment by oojacoboo** [comment] 2022-06-12 03:23
Closing out this issue as it's assumed to be cache related with different implementation specific solutions, most of which are outside the scope of this lib.

**Closed by oojacoboo** 2022-06-12 03:23 UTC
Labels: additional info needed
