### ISSUE TITLE
How to document a query for the schema?

### ISSUE THREAD

**Issue by MarianNapi** [thecodingmachine/graphqlite#265] opened 2020-05-22 08:53 UTC
Is there a way to add comments to queries, types etc. so they come up in the schema.graphql?

Like in this example from Magento:
![schema](https://user-images.githubusercontent.com/65761018/82650089-7be66180-9c1a-11ea-9b8c-63ee868598c2.PNG)

**Comment by MarianNapi** [comment] 2020-05-22 09:34
Suddenly the commentary appears in the schema but not properly formatted:

![comment](https://user-images.githubusercontent.com/65761018/82653830-18f7c900-9c20-11ea-88a9-f892942a9bae.PNG)

This is how I added the comment: 
![product](https://user-images.githubusercontent.com/65761018/82653915-39278800-9c20-11ea-8fb6-0d4418df6511.PNG)

**Comment by moufmouf** [comment] 2020-05-22 13:08
Exactly, the comment from your PHP code queries/fields is propagated to the schema.
I probably need to document this properly.

When you say "not properly formatted", you are referring to the "new line" in front of the comment, right?

**Comment by moufmouf** [comment] 2020-05-22 13:08
(also, congrats on your first issue on Github! :tada: ) :smile:

**Comment by MarianNapi** [comment] 2020-05-22 13:31
Thanks 😄

Yeah I didn't find any hint on where to comment to get it to the schema.
And yes by "not properly formatted" I mean the new line but also the multiple quotation marks in front and behind the comment :)

**Comment by oneserv-heuser** [comment] 2020-06-25 09:01
A really nice feature to have would also be to be able to document the parameters for a function, as by now the PHPDoc gets ignored for paramters and is not parsed into the schema. Or is there already a way to do it and we're doing it wrong?

**Comment by moufmouf** [comment] 2020-06-25 14:03
Indeed, pretty good idea!
I'll keep the issue open until we implement it.

**Comment by oojacoboo** [comment] 2021-03-29 16:12
Duplicate of #289

**Closed by oojacoboo** 2021-03-29 16:12 UTC
